package com.wing.tree.salamander.bible.constant

internal const val ONE = 1

internal const val EMPTY = ""
internal const val SPACE = " "

internal val titles = mapOf(
    1 to "창세기",
    2 to "출애굽기",
    3 to "레위기",
    4 to "민수기",
    5 to "신명기",
    6 to "여호수아",
    7 to "사사기",
    8 to "롯기",
    9 to "사무엘상",
    10 to "사무엘하",
    11 to "열왕기상",
    12 to "열왕기하",
    13 to "역대상",
    14 to "역대하",
    15 to "에스라",
    16 to "느헤미야",
    17 to "에스더",
    18 to "욥기",
    19 to "시편",
    20 to "잠언",
    21 to "전도서",
    22 to "아가",
    23 to "이사야",
    24 to "예레미아",
    25 to "예레미야애가",
    26 to "에스겔",
    27 to "다니엘",
    28 to "호세아",
    29 to "요엘",
    30 to "아모스",
    31 to "오바댜",
    32 to "요나",
    33 to "미가",
    34 to "나훔",
    35 to "하박국",
    36 to "스바냐",
    37 to "학개",
    38 to "스가랴",
    39 to "말라기",
    40 to "마태복음",
    41 to "마가복음",
    42 to "누가복음",
    43 to "요한복음",
    44 to "사도행전",
    45 to "로마서",
    46 to "고린도전서",
    47 to "고린도후서",
    48 to "갈라디아서",
    49 to "에베소서",
    50 to "빌립보서",
    51 to "골로새서",
    52 to "데살로니가전서",
    53 to "데살로니가후서",
    54 to "디모데전서",
    55 to "디모데후서",
    56 to "디도서",
    57 to "빌레몬서",
    58 to "히브리서",
    59 to "야고보서",
    60 to "베드로전서",
    61 to "베드로후서",
    62 to "요한일서",
    63 to "요한이서",
    64 to "요한삼서",
    65 to "유다서",
    66 to "요한계시록"
)